using System;

namespace org.in2bits.MyOle2.Metadata
{
	// Token: 0x0200003E RID: 62
	public class SummaryInformationSection : MetadataStream.Section
	{
		// Token: 0x06000226 RID: 550 RVA: 0x0000A858 File Offset: 0x00009858
		public SummaryInformationSection()
		{
			base.FormatId = SummaryInformationSection.FORMAT_ID;
			this.CodePage = new short?(1252);
			this.LastSavedBy = Environment.UserName;
			this.NameOfCreatingApplication = "org.in2bits.MyXls";
			this.Comments = "This workbook generated by MyXls! http://sourceforge.net/myxls";
			this.CreateTimeDate = new DateTime?(DateTime.Now);
		}

		// Token: 0x170000D0 RID: 208
		// (get) Token: 0x06000227 RID: 551 RVA: 0x0000A8B7 File Offset: 0x000098B7
		// (set) Token: 0x06000228 RID: 552 RVA: 0x0000A8C5 File Offset: 0x000098C5
		public short? CodePage
		{
			get
			{
				return (short?)base.GetProperty(1U);
			}
			set
			{
				base.SetProperty(1U, Property.Types.VT_I2, value);
			}
		}

		// Token: 0x170000D1 RID: 209
		// (get) Token: 0x06000229 RID: 553 RVA: 0x0000A8D5 File Offset: 0x000098D5
		// (set) Token: 0x0600022A RID: 554 RVA: 0x0000A8E3 File Offset: 0x000098E3
		public string Title
		{
			get
			{
				return (string)base.GetProperty(2U);
			}
			set
			{
				base.SetProperty(2U, Property.Types.VT_LPSTR, value);
			}
		}

		// Token: 0x170000D2 RID: 210
		// (get) Token: 0x0600022B RID: 555 RVA: 0x0000A8EF File Offset: 0x000098EF
		// (set) Token: 0x0600022C RID: 556 RVA: 0x0000A8FD File Offset: 0x000098FD
		public string Subject
		{
			get
			{
				return (string)base.GetProperty(3U);
			}
			set
			{
				base.SetProperty(3U, Property.Types.VT_LPSTR, value);
			}
		}

		// Token: 0x170000D3 RID: 211
		// (get) Token: 0x0600022D RID: 557 RVA: 0x0000A909 File Offset: 0x00009909
		// (set) Token: 0x0600022E RID: 558 RVA: 0x0000A917 File Offset: 0x00009917
		public string Author
		{
			get
			{
				return (string)base.GetProperty(4U);
			}
			set
			{
				base.SetProperty(4U, Property.Types.VT_LPSTR, value);
			}
		}

		// Token: 0x170000D4 RID: 212
		// (get) Token: 0x0600022F RID: 559 RVA: 0x0000A923 File Offset: 0x00009923
		// (set) Token: 0x06000230 RID: 560 RVA: 0x0000A931 File Offset: 0x00009931
		public string Keywords
		{
			get
			{
				return (string)base.GetProperty(5U);
			}
			set
			{
				base.SetProperty(5U, Property.Types.VT_LPSTR, value);
			}
		}

		// Token: 0x170000D5 RID: 213
		// (get) Token: 0x06000231 RID: 561 RVA: 0x0000A93D File Offset: 0x0000993D
		// (set) Token: 0x06000232 RID: 562 RVA: 0x0000A94B File Offset: 0x0000994B
		public string Comments
		{
			get
			{
				return (string)base.GetProperty(6U);
			}
			set
			{
				base.SetProperty(6U, Property.Types.VT_LPSTR, value);
			}
		}

		// Token: 0x170000D6 RID: 214
		// (get) Token: 0x06000233 RID: 563 RVA: 0x0000A957 File Offset: 0x00009957
		// (set) Token: 0x06000234 RID: 564 RVA: 0x0000A965 File Offset: 0x00009965
		public string Template
		{
			get
			{
				return (string)base.GetProperty(7U);
			}
			set
			{
				base.SetProperty(7U, Property.Types.VT_LPSTR, value);
			}
		}

		// Token: 0x170000D7 RID: 215
		// (get) Token: 0x06000235 RID: 565 RVA: 0x0000A971 File Offset: 0x00009971
		// (set) Token: 0x06000236 RID: 566 RVA: 0x0000A97F File Offset: 0x0000997F
		public string LastSavedBy
		{
			get
			{
				return (string)base.GetProperty(8U);
			}
			set
			{
				base.SetProperty(8U, Property.Types.VT_LPSTR, value);
			}
		}

		// Token: 0x170000D8 RID: 216
		// (get) Token: 0x06000237 RID: 567 RVA: 0x0000A98B File Offset: 0x0000998B
		// (set) Token: 0x06000238 RID: 568 RVA: 0x0000A99A File Offset: 0x0000999A
		public string RevisionNumber
		{
			get
			{
				return (string)base.GetProperty(9U);
			}
			set
			{
				base.SetProperty(9U, Property.Types.VT_LPSTR, value);
			}
		}

		// Token: 0x170000D9 RID: 217
		// (get) Token: 0x06000239 RID: 569 RVA: 0x0000A9A7 File Offset: 0x000099A7
		// (set) Token: 0x0600023A RID: 570 RVA: 0x0000A9B6 File Offset: 0x000099B6
		public DateTime? TotalEditingTime
		{
			get
			{
				return (DateTime?)base.GetProperty(10U);
			}
			set
			{
				base.SetProperty(10U, Property.Types.VT_FILETIME, value);
			}
		}

		// Token: 0x170000DA RID: 218
		// (get) Token: 0x0600023B RID: 571 RVA: 0x0000A9C8 File Offset: 0x000099C8
		// (set) Token: 0x0600023C RID: 572 RVA: 0x0000A9D7 File Offset: 0x000099D7
		public DateTime? LastPrinted
		{
			get
			{
				return (DateTime?)base.GetProperty(11U);
			}
			set
			{
				base.SetProperty(11U, Property.Types.VT_FILETIME, value);
			}
		}

		// Token: 0x170000DB RID: 219
		// (get) Token: 0x0600023D RID: 573 RVA: 0x0000A9E9 File Offset: 0x000099E9
		// (set) Token: 0x0600023E RID: 574 RVA: 0x0000A9F8 File Offset: 0x000099F8
		public DateTime? CreateTimeDate
		{
			get
			{
				return (DateTime?)base.GetProperty(12U);
			}
			set
			{
				base.SetProperty(12U, Property.Types.VT_FILETIME, value);
			}
		}

		// Token: 0x170000DC RID: 220
		// (get) Token: 0x0600023F RID: 575 RVA: 0x0000AA0A File Offset: 0x00009A0A
		// (set) Token: 0x06000240 RID: 576 RVA: 0x0000AA19 File Offset: 0x00009A19
		public DateTime? LastSavedTimeDate
		{
			get
			{
				return (DateTime?)base.GetProperty(13U);
			}
			set
			{
				base.SetProperty(13U, Property.Types.VT_FILETIME, value);
			}
		}

		// Token: 0x170000DD RID: 221
		// (get) Token: 0x06000241 RID: 577 RVA: 0x0000AA2B File Offset: 0x00009A2B
		// (set) Token: 0x06000242 RID: 578 RVA: 0x0000AA3A File Offset: 0x00009A3A
		public int? NumberOfPages
		{
			get
			{
				return (int?)base.GetProperty(14U);
			}
			set
			{
				base.SetProperty(14U, Property.Types.VT_I4, value);
			}
		}

		// Token: 0x170000DE RID: 222
		// (get) Token: 0x06000243 RID: 579 RVA: 0x0000AA4B File Offset: 0x00009A4B
		// (set) Token: 0x06000244 RID: 580 RVA: 0x0000AA5A File Offset: 0x00009A5A
		public int? NumberOfWords
		{
			get
			{
				return (int?)base.GetProperty(15U);
			}
			set
			{
				base.SetProperty(15U, Property.Types.VT_I4, value);
			}
		}

		// Token: 0x170000DF RID: 223
		// (get) Token: 0x06000245 RID: 581 RVA: 0x0000AA6B File Offset: 0x00009A6B
		// (set) Token: 0x06000246 RID: 582 RVA: 0x0000AA7A File Offset: 0x00009A7A
		public int? NumberOfCharacters
		{
			get
			{
				return (int?)base.GetProperty(16U);
			}
			set
			{
				base.SetProperty(16U, Property.Types.VT_I4, value);
			}
		}

		// Token: 0x170000E0 RID: 224
		// (get) Token: 0x06000247 RID: 583 RVA: 0x0000AA8B File Offset: 0x00009A8B
		// (set) Token: 0x06000248 RID: 584 RVA: 0x0000AA9A File Offset: 0x00009A9A
		public string NameOfCreatingApplication
		{
			get
			{
				return (string)base.GetProperty(18U);
			}
			set
			{
				base.SetProperty(18U, Property.Types.VT_LPSTR, value);
			}
		}

		// Token: 0x170000E1 RID: 225
		// (get) Token: 0x06000249 RID: 585 RVA: 0x0000AAA7 File Offset: 0x00009AA7
		// (set) Token: 0x0600024A RID: 586 RVA: 0x0000AAB6 File Offset: 0x00009AB6
		public int? Security
		{
			get
			{
				return (int?)base.GetProperty(19U);
			}
			set
			{
				base.SetProperty(19U, Property.Types.VT_I4, value);
			}
		}

		// Token: 0x04000235 RID: 565
		private const uint ID_CODEPAGE = 1U;

		// Token: 0x04000236 RID: 566
		private const uint ID_TITLE = 2U;

		// Token: 0x04000237 RID: 567
		private const uint ID_SUBJECT = 3U;

		// Token: 0x04000238 RID: 568
		private const uint ID_AUTHOR = 4U;

		// Token: 0x04000239 RID: 569
		private const uint ID_KEYWORDS = 5U;

		// Token: 0x0400023A RID: 570
		private const uint ID_COMMENTS = 6U;

		// Token: 0x0400023B RID: 571
		private const uint ID_TEMPLATE = 7U;

		// Token: 0x0400023C RID: 572
		private const uint ID_LAST_SAVED_BY = 8U;

		// Token: 0x0400023D RID: 573
		private const uint ID_REVISION_NUMBER = 9U;

		// Token: 0x0400023E RID: 574
		private const uint ID_TOTAL_EDITING_TIME = 10U;

		// Token: 0x0400023F RID: 575
		private const uint ID_LAST_PRINTED = 11U;

		// Token: 0x04000240 RID: 576
		private const uint ID_CREATE_TIME_DATE = 12U;

		// Token: 0x04000241 RID: 577
		private const uint ID_LAST_SAVED_TIME_DATE = 13U;

		// Token: 0x04000242 RID: 578
		private const uint ID_NUMBER_OF_PAGES = 14U;

		// Token: 0x04000243 RID: 579
		private const uint ID_NUMBER_OF_WORDS = 15U;

		// Token: 0x04000244 RID: 580
		private const uint ID_NUMBER_OF_CHARACTERS = 16U;

		// Token: 0x04000245 RID: 581
		private const uint ID_THUMBNAIL = 17U;

		// Token: 0x04000246 RID: 582
		private const uint ID_NAME_OF_CREATING_APPLICATION = 18U;

		// Token: 0x04000247 RID: 583
		private const uint ID_SECURITY = 19U;

		// Token: 0x04000248 RID: 584
		private static readonly byte[] FORMAT_ID = new byte[]
		{
			224,
			133,
			159,
			242,
			249,
			79,
			104,
			16,
			171,
			145,
			8,
			0,
			43,
			39,
			179,
			217
		};
	}
}
